@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\Program Files\IAR Systems\Embedded Workbench 6.0\common\bin\cspybat" "D:\Program Files\IAR Systems\Embedded Workbench 6.0\avr\bin\avrproc.dll" "D:\Program Files\IAR Systems\Embedded Workbench 6.0\avr\bin\avrJtagIce-mkII.dll"  %1 --plugin "D:\Program Files\IAR Systems\Embedded Workbench 6.0\avr\bin\avrlibsupportbat.dll" --backend -B "--cpu=m1281" "--enhanced_core" "-p" "D:\Program Files\IAR Systems\Embedded Workbench 6.0\avr\Config\iom1281.ddf" "--eeprom_size" "4096" "-d" "jtagIceMkII" "--jtagice_clock=100000" "--jtagice_leave_timers_running" "--jtagice_preserve_eeprom" "--jtagice_do_hardware_reset" "--jtagice_restore_fuse" "--jtagicemkII_use_software_breakpoints" "--drv_communication=USB" 


